name: CD Pipeline

on:
  workflow_run:
    workflows:  ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull pankajadhana97/cicd-pipeline:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f cicd-pipeline-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 80:80 --name cicd-pipeline-container pankajadhana97/cicd-pipeline
