name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build -t cicd-pipeline .
      - name: Push to Dockerhub
        run: docker push pankajadhana97/cicd-pipeline:latest
